### ISSUE TITLE
Webhook and multiple files

### ISSUE THREAD

**Issue by thenitai** [versity/versitygw#606] opened 2024-06-04 09:51 UTC
We've now finally implemented a whole workflow for uploading files with the webhook as discussed at #475

It works perfect but only ever when one uploads a file sequential, i.e., if I upload 2 or more files simultaneously the event only ever shows the first file of the batch. I've tried it with Cyberduck and WinSCP.

I've tried it with custom events and without, but it made no difference. Is there something I need to change or configure?

**Comment by thenitai** [comment] 2024-06-04 10:05
Update:

I used Haproxy with two VersityGW servers. As soon as I stop one server it works with multiple files. Would stickiness help in this regard or is a load balancer configuration not supported?

**Comment by benmcclelland** [comment] 2024-06-04 15:18
@thenitai Just to make sure I understand the setup, the load balancer is distributing requests between two versitygw endpoints. And each of these is set to send events to the same webhook?

I wouldn't expect the load balancer to have any effect on how the events are sent to the webhook.  Could you verify that both versitygw instances can send to the webhook if sending requests directly to them? Could be that one of the gateways is unable to connect to the webhook for some reason?

I think we might have a bug where if the webhook is not accessible when the gateway first starts, then it will never send any events to that webhook. We may need to change this so that it starts sending events whenever the connection becomes available.

**Comment by thenitai** [comment] 2024-06-04 18:31
Both versityGW servers work when I only have one running behind the load balancer.

haproxy -> versityGW-ONE - WORKS
haproxy -> versityGW-TWO - WORKS
haproxy -> versityGW-ONE & versityGW-TWO - Only ONE file webhook request is sent

Does that make sense?

**Comment by benmcclelland** [comment] 2024-06-04 18:56
> Both versityGW servers work when I only have one running behind the load balancer.
> 
> haproxy -> versityGW-ONE - WORKS haproxy -> versityGW-TWO - WORKS haproxy -> versityGW-ONE & versityGW-TWO - Only ONE file webhook request is sent
> 
> Does that make sense?

Yes, thank you. I'll see if I can reproduce this over here.

**Comment by benmcclelland** [comment] 2024-06-04 21:29
Ok, I ran a test that looks like its working ok. Let me know if this test is not testing the case you are looking for.  I have a simple webhook endpoint that just prints the client address and the payload:
```go
package main

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"strings"
)

func main() {
	http.HandleFunc("/s3events", func(w http.ResponseWriter, r *http.Request) {
		defer r.Body.Close()
		buf := new(strings.Builder)
		io.Copy(buf, r.Body)
		fmt.Println(r.RemoteAddr, buf.String())
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

I started two gateways on different hosts, both pointing at the same webhook endpoint:
```
versitygw -a test -s test --event-webhook-url http://172.21.0.150:8080/s3events posix /mnt/gwtest
```

I see the test messages pop up in the webhook app:
```
172.21.0.150:54314 {"Bucket":"Test-Bucket","Event":"s3:TestEvent","Service":"S3","Time":"2024-06-04T19:23:34Z"}
172.21.0.151:38200 {"Bucket":"Test-Bucket","Event":"s3:TestEvent","Service":"S3","Time":"2024-06-04T19:23:35Z"}
```

I configured haproxy on one of the hosts to load balance across both of them:
```
# cat /etc/haproxy/haproxy.cfg 
global
    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

frontend  main *:5000
    default_backend             gw

backend gw
    balance     roundrobin
    server  gw1 172.21.0.150:7070
    server  gw2 172.21.0.151:7070
```

And I setup my client to point to the haproxy listening port:
```
export AWS_SECRET_ACCESS_KEY=test               
export AWS_ACCESS_KEY_ID=test
export AWS_ENDPOINT_URL=http://172.21.0.151:5000
export AWS_REGION=us-east-1
```

I then ran the following to upload 10 objects at the same time:
```
% for i in $(seq 1 10); do aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i & done; wait 
[2] 65635
[3] 65636
[4] 65637
[5] 65638
[6] 65639
[7] 65640
[8] 65641
[9] 65642
[10] 65643
[11] 65644
upload: ./file1mb to s3://testbucket1/testfile1mb10               
[11]  + done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
upload: ./file1mb to s3://testbucket1/testfile1mb9                
[10]  + done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
upload: ./file1mb to s3://testbucket1/testfile1mb1                
[2]    done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
upload: ./file1mb to s3://testbucket1/testfile1mb5                
upload: ./file1mb to s3://testbucket1/testfile1mb3                
[6]    done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
[4]    done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
upload: ./file1mb to s3://testbucket1/testfile1mb7                
upload: ./file1mb to s3://testbucket1/testfile1mb8                
[8]  - done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
[9]  + done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
upload: ./file1mb to s3://testbucket1/testfile1mb2                
[3]    done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
upload: ./file1mb to s3://testbucket1/testfile1mb4                
[5]  - done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
upload: ./file1mb to s3://testbucket1/testfile1mb6                
[7]  + done       aws s3 cp ./file1mb s3://testbucket1/testfile1mb$i
```

And I see all events in the webhook app:
```
172.21.0.151:38326 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:17Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb10"},"object":{"key":"testfile1mb10","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"1"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.150:54404 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:17Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb9"},"object":{"key":"testfile1mb9","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"1"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.151:38326 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:17Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb1"},"object":{"key":"testfile1mb1","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"2"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.151:38326 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:18Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb3"},"object":{"key":"testfile1mb3","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"3"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.150:54404 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:18Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb5"},"object":{"key":"testfile1mb5","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"2"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.151:38326 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:18Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb8"},"object":{"key":"testfile1mb8","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"4"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.151:38326 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:18Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb7"},"object":{"key":"testfile1mb7","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"5"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.150:54404 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:18Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb2"},"object":{"key":"testfile1mb2","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"3"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.150:54404 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:18Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb4"},"object":{"key":"testfile1mb4","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"4"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
172.21.0.150:54404 {"Records":[{"eventVersion":"2.2","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2024-06-04T21:23:18Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"PrincipalId":"test"},"requestParameters":{"sourceIPAddress":"172.21.0.151"},"responseElements":{"x-amz-request-id":"","x-amz-id-2":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"webhook-global","bucket":{"name":"testbucket1","ownerIdentity":{"PrincipalId":"test"},"arn":"arn:aws:s3:::/testbucket1/testfile1mb6"},"object":{"key":"testfile1mb6","size":1048576,"eTag":"b6d81b360a5672d80c27430f39153e2c","versionId":null,"sequencer":"5"}},"glacierEventData":{"restoreEventData":{"lifecycleRestorationExpiryTime":"","lifecycleRestoreStorageClass":""}}}]}
```

Is there something different in your setup that I might not have correct here?

**Comment by thenitai** [comment] 2024-06-04 22:53
I have two backends for testing. One listens over TCP, and the other over HTTP. I adjusted my backend route to match yours.

One file works without any issues. If I upload two or more at once, I always only get one event to my webhook.

It does work as soon as I only use one gw server...

Now sure how else to debug it. You can ping me directly too so not to litter up the thread here.

**Comment by benmcclelland** [comment] 2024-06-04 23:50
The route just needs to match whatever the webhook server is expecting. In my test case, my webhook server is only handling `/s3events`.  Would you be able to try the example webhook server that I pasted in above? It doesnt take any options. Just run `go build` and run the resulting executable.  It listens on port `8080` for the `/s3events` route.

When running both gateways, do you see both test events at the webhook server? For example, mine shows this message for each gateway that I run:
```
172.21.0.150:54314 {"Bucket":"Test-Bucket","Event":"s3:TestEvent","Service":"S3","Time":"2024-06-04T19:23:34Z"}
```

If there are any errors from versitygw sending to the webhook endpoint, they would be written to stderr. They would be something like one of these:
```
	fmt.Fprintf(os.Stderr, "failed to parse event data: %v\n", err.Error())
	fmt.Fprintf(os.Stderr, "failed to create webhook event request: %v\n", err.Error())
	fmt.Fprintf(os.Stderr, "failed to send webhook event: %v\n", err.Error())
```

**Comment by benmcclelland** [comment] 2024-06-06 15:05
I'm going to close this issue as not reproducible since the test webhook seems to be working as expected. If there is a webhook that fails, feel free to reopen this with more details of a failing case that we can try to reproduce. Since the gateway webhook events dont have any knowledge of a load balancer setup, I'm assuming the issue might be at the webhook side not able to accept events from multiple gateways at the same time.

**Closed by benmcclelland** 2024-06-06 15:05 UTC
Labels: bug

**Comment by thenitai** [comment] 2024-06-06 17:24
I have over twenty app servers that listen for webhooks. Webhooks come in without an issue. It's just the Haproxy to versityGW setup that is causing an issue. I keep on experimenting, but so far have no success with multiple servers.

**Comment by thenitai** [comment] 2024-06-06 22:08
> I'm going to close this issue as not reproducible since the test webhook seems to be working as expected. If there is a webhook that fails, feel free to reopen this with more details of a failing case that we can try to reproduce. Since the gateway webhook events dont have any knowledge of a load balancer setup, I'm assuming the issue might be at the webhook side not able to accept events from multiple gateways at the same time.

Found the issue. One server had an older version of versityGW, one that didn't include the webhook feature. Duh... Sorry about this.
